import { Inter , Montserrat , Lexend_Deca } from 'next/font/google'
// import { Inter } from 'next/font/google'
import './globals.css'
import StickyNavbar from './Components/NavBar/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>xx
        {children}</body>
    </html>
  )
}
